### ISSUE TITLE
pip 安装出错

### ISSUE THREAD

**Issue by StephenPCG** [jpush/jpush-api-python-client#19]
```
pip install git+https://github.com/jpush/jpush-api-python-client
Collecting git+https://github.com/jpush/jpush-api-python-client
  Cloning https://github.com/jpush/jpush-api-python-client to /var/folders/g0/r2t_1w112x17pcq_wycw61kc0000gn/T/pip-PkRBZd-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/g0/r2t_1w112x17pcq_wycw61kc0000gn/T/pip-PkRBZd-build/setup.py", line 6, in <module>
        from jpush import __version__
      File "jpush/__init__.py", line 2, in <module>
        from .core import JPush
      File "jpush/core.py", line 5, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /var/folders/g0/r2t_1w112x17pcq_wycw61kc0000gn/T/pip-PkRBZd-build
```

由于pypi中还没有更新3.0.2，我在项目的requirements.txt中只能直接从github来安装jpush。在干净的virtualenv中pip -r requirements.txt就会报如上的错误（requirements.txt中也写了requests，并且在jpush之前）。建议不要在 setup.py 中 import jpush，以避免这种问题。

在线上部署时，我不能先单独安装requests再安装requirements.txt，例如我们使用saltstack进行部署：

```
some-virtual-env:
  virtualenv.managed:
    - name: /path/to/some-virtual-env/
    - requirements: /path/to/requirements.txt
```

如果我要单独先安装 requests 库，就得现有 some-virtual-env，循环依赖了。

最关键的，还是尽快将最新版推到pypi吧，距上一次commit都已经8个多月了，还不推pypi，难道没人用么？

**Comment by hupantingxue** [comment]
python-jpush lastest version:
https://pypi.python.org/pypi/jpush/3.1.0
