### ISSUE TITLE
jpush.common.Unauthorized

### ISSUE THREAD

**Issue by gclsoft** [jpush/jpush-api-python-client#20]
```
import jpush as jpush
from conf import app_key, master_secret
_jpush = jpush.JPush(app_key, master_secret)

push = _jpush.create_push()
push.audience = jpush.all_
ios_msg = jpush.ios(alert="Hello, IOS JPush!", badge="+1", sound="a.caf", extras={'k1':'v1'})
android_msg = jpush.android(alert="Hello, android msg")
push.notification = jpush.notification(alert="Hello, JPush!", android=android_msg, ios=ios_msg)
push.platform = jpush.all_
push.send()
```

```
Traceback (most recent call last):
  File "/Applications/Aptana Studio 3/plugins/org.python.pydev_3.0.0.1388187472/pysrc/pydevd.py", line 1479, in <module>
    debugger.run(setup['file'], None, None)
  File "/Applications/Aptana Studio 3/plugins/org.python.pydev_3.0.0.1388187472/pysrc/pydevd.py", line 1125, in run
    pydev_imports.execfile(file, globals, locals)  #execute the script
  File "/Users/apple/node/undo4096/tool/videoPei/test.py", line 22, in <module>
    push.send()
  File "build/bdist.macosx-10.10-x86_64/egg/jpush/push/core.py", line 46, in send
  File "build/bdist.macosx-10.10-x86_64/egg/jpush/core.py", line 45, in _request
jpush.common.Unauthorized
```

**Comment by gclsoft** [comment]
```
        if response.status_code == 401:
            raise common.Unauthorized
```
But my network is ok.

**Comment by gclsoft** [comment]
I've set config in config.py.  Please help me

**Comment by gclsoft** [comment]
````
pydev debugger: process 27014 is connecting

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/apple/node/undo4096/tool/videoPei/btc/huobi/btcChina/push.py", line 13, in <module>
    push.send()
  File "/Library/Python/2.7/site-packages/jpush/push/core.py", line 46, in send
    common.PUSH_URL, 'application/json', version=3)
  File "/Library/Python/2.7/site-packages/jpush/core.py", line 45, in _request
    raise common.Unauthorized
jpush.common.Unauthorized

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import jpush as jpush
from conf import app_key, master_secret
_jpush = jpush.JPush(app_key, master_secret)
push = _jpush.create_push()
push.audience = jpush.all_
ios_msg = jpush.ios(alert="Hello, IOS JPush!", badge="+1", sound="a.caf", extras={'k1':'v1'})
push.notification = jpush.notification(alert="Hello, JPush!")
push.options = {"time_to_live":86400, "sendno":12345, "apns_production":True}
push.platform = jpush.platform("ios")
push.send()

Helpless

**Comment by gclsoft** [comment]
app_key = ' '
master_secret = ' '
remove u
