### ISSUE TITLE
安装jpush时报错

### ISSUE THREAD

**Issue by ZhangBohan** [jpush/jpush-api-python-client#21]
```
Downloading/unpacking jpush (from -r requirements.txt (line 29))
  Downloading jpush-3.1.1.tar.gz
  Running setup.py (path:/opt/lambda/env/build/jpush/setup.py) egg_info for package jpush
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/opt/lambda/env/build/jpush/setup.py", line 6, in <module>
        from jpush import __version__
      File "jpush/__init__.py", line 2, in <module>
        from .core import JPush
      File "jpush/core.py", line 5, in <module>
        import requests
    ImportError: No module named requests
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/opt/lambda/env/build/jpush/setup.py", line 6, in <module>

    from jpush import __version__

  File "jpush/__init__.py", line 2, in <module>

    from .core import JPush

  File "jpush/core.py", line 5, in <module>

    import requests

ImportError: No module named requests
```

**Comment by hupantingxue** [comment]
Please refer to: <a href="https://www.jpush.cn/qa/?qa=12630/python%E8%99%9A%E6%8B%9F%E7%8E%AF%E5%A2%83%E4%B8%8Bpip-install-jpush%E6%8F%90%E7%A4%BA%E6%B2%A1%E6%9C%89requests%E6%A8%A1%E5%9D%97">python虚拟环境下pip install jpush提示没有requests模块</a>
